import Head from "next/head";
import CreateEvent from "../components/CreateEvent";


import { useEffect } from "react";

const CreateEventPage = (props) => {

    useEffect(() => {
       if(props) console.log(props); 
    }, [props])

    return (
        props.cred &&
        <div>
            <Head>
                <title>Title</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CreateEvent />
            </main>
        </div>
    )
}

export default CreateEventPage;