import Head from "next/head";
import Footer from "../components/Layout/Footer";
import PrimarySearchAppBar from "../components/Layout/PrimarySearchAppBar";
import Hero from "../components/HomeSections/Hero";
import WhyGlean from "../components/HomeSections/WhyGlean";
import MeetTopVolunteers from "../components/HomeSections/MeetTopVolunteers";
import { useEffect } from "react";

export default function Home(props) {

  useEffect(() => {
    if(props) console.log(props);
  }, [props])
  
  return (
    props.cred &&
    <div>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PrimarySearchAppBar cred={props.cred}/>
        <Hero />
        <WhyGlean />
        <MeetTopVolunteers />
        <Footer />
      </main>
    </div>
  );
}
