import Search from "../components/Search";
import Head from 'next/head';
import PrimarySearchAppBar from "../components/Layout/PrimarySearchAppBar";

export default function Home(props) {
    return (
      <div>
        <Head>
          <title>Title</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
            <Search />
        </main>
      </div>
    );
  }
  