import Head from "next/head";
import SignInSide from "../components/Login";
import PrimarySearchAppBar from "../components/Layout/PrimarySearchAppBar";


import { useEffect } from "react";

const HomePage = (props) => {

    useEffect(() => {
       if(props) console.log(props); 
    }, [props])

    return (
        props.cred &&
        <div>
            <Head>
                <title>Title</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PrimarySearchAppBar/>
                <SignInSide setCredentials={props.setCred}/>
            </main>
        </div>
    )
}

export default HomePage;